### ISSUE TITLE
'mw domain get' only works with 'project-id' in context

### ISSUE THREAD

**Issue by tillwestpfahl** [mittwald/cli#184]
Works only if it has been set via `mw context set --project-id`, but not with flag `--project-id`.

![image](https://github.com/mittwald/cli/assets/78540379/da89a5e9-6722-4f08-955c-d3c3199901a5)

The projectID should also not be necessary to get a Domain, according to the API -> [here](https://api.mittwald.de/v2/docs/#/Domain/domain-get-domain).

But the command enforces it: 

```
❯ mw domain get <my-domain-id>

ERROR  No project ID given. Please consult the --help page of this command or set a default project with 'mittwald context set --project-id <project-id>'
```

**Comment by martin-helmich** [comment]
Oh, yeah. That flag is supported because you can also specify a domain by its hostname -- in which case, the project ID is needed to first list the domains of that project, and then filtering locally by hostname. I think, in the future this might be solved more elegantly using the upcoming short-id redirect feature in the API.

However, I concur that the project id should not be required in any case when a domain is specified by its ID; I'll take a look shortly.
