### ISSUE TITLE
Output format JSON should always use ISO dates

### ISSUE THREAD

**Issue by LukasFritzeDev** [mittwald/cli#60]
When running the get command `mw database mysql get` with the flag `--output json` the dates are formatted as an ISO date string as expected.

```
~ ❯ mw database mysql get e404f33f-fce3-4f5b-ad47-************ --output json
{
  "createdAt": "2023-09-10T14:57:03.000Z",
  "id": "e404f33f-fce3-4f5b-ad47-************",
  "updatedAt": "2023-09-10T14:57:05.000Z",
  ...
}
```

Using the list command `mw database mysql list --output json` the date is shown in a human readable format.
```
~ ❯ mw database mysql list --output json                                    
[
  {
    "id": "e404f33f-fce3-4f5b-ad47-************",
    "createdAt": "25 minutes ago",
    ...
  }
]
```

If `--output json` is used, for all commands dates should be formatted as ISO dates.

**Comment by martin-helmich** [comment]
This is broken by design; I think list output (especially the JSON/YAML renderings of those) needs to be thoroughly re-thought, in any case. Right now, a `get` command will output the raw API response when invoked with `--output=json`, but a `list` command will instead output the rendered table columns, which is not a consistent behaviour, at all. Same goes for filtering and sorting (ref. #58 and #59), both of which are also highly unpredictable.
